### ISSUE TITLE
Slight copy change on Teach-specific Welcome email

### ISSUE THREAD

**Issue by hannahkane** [mozilla/webmaker-mailroom#30]
Should read (changes are in italics):

If you're teaching the web in your local community, we want to know about it. Adding your club, program or classroom to our community map *[link community map to /mozilla-web-clubs/]* is simple, and allows us to send you locally relevant resources. If you don't have a local group yet, *reply to this email to* let us know you're interested *[no link]*, and we'll be in touch with you shortly.

**Comment by secretrobotron** [comment]
Note: "reply to this email" isn't special in any way. @hannahkane was just showing that it's not in the current template.

**Comment by secretrobotron** [comment]
For https://github.com/mozilla/id.webmaker.org/issues/11 (QA)
