### ISSUE TITLE
Enable localization

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-mailroom#34]
This is more fact-finding than anything (so far):
* Is there any localization plugged into this project already?
* If so, where is it?
* If not, what do we need to do to enable it?

We're going to need this when we start localizing the app. e.g. The Welcome email should be localized.

**Comment by jbuck** [comment]
yes, it's key-value replacement like our other nunjucks-based apps. Take a look at the existing emails for specifics, but you basically define a key and nunjucks chooses the correct one based on the locale provided in the render function

**Comment by secretrobotron** [comment]
Ah nice. @jbuck it will definitely switch languages based on user locale? (Is there a test or something?)
We'll need to tell login/api/id how to specify that, I'm guessing.

**Comment by jbuck** [comment]
Yes and yes
